# Generated by Django 5.0.3 on 2024-05-17 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("success", "0006_template"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="link",
            name="name",
        ),
    ]
