# Generated by Django 5.0.3 on 2024-05-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('success', '0007_delete_link_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='type',
            field=models.FloatField(default=0.5),
        ),
    ]
