# Generated by Django 5.0.3 on 2024-05-17 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("success", "0008_link_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="link",
            old_name="type",
            new_name="value",
        ),
    ]
