# Generated by Django 5.0.3 on 2024-05-17 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('success', '0009_link_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='factor',
            name='value',
            field=models.FloatField(default=0.5),
        ),
    ]
