# Generated by Django 5.0.3 on 2024-06-12 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('success', '0010_factor_value'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='factor',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='unique name for factor'),
        ),
    ]
